#!/usr/bin/env bash
#====================================
# @file   : bootstrap
# @brief  : bash script to install the dependencies needed to
#           automatically generate the assets for Assets-Production
#           from the Assets-Masters source
#====================================
# Copyright (C) 2026 Evert Vorster, Stephen G. Tuggy, Roy Falk,
# Benjamen R. Meyer, SGD1953, and other vsUTCS contributors.
#
# This file is part of Vega Strike: Upon the Coldest Sea ("vsUTCS").
#
# vsUTCS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# vsUTCS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vsUTCS.  If not, see <https://www.gnu.org/licenses/>.


apt update
apt install nvidia-texture-tools
apt install texlive-games

/usr/bin/env python3 -m venv ./.venv
./.venv/bin/pip install pillow>=10.4.0
