#!/usr/bin/env bash
#====================================
# @file   : bootstrap
# @brief  : bash script to install the dependencies needed to
#           automatically generate the assets for Assets-Production
#           from the Assets-Masters source
#====================================
# Copyright (C) 2026 Evert Vorster, Stephen G. Tuggy, Roy Falk,
# Benjamen R. Meyer, SGD1953, and other vsUTCS contributors.
#
# This file is part of Vega Strike: Upon the Coldest Sea ("vsUTCS").
#
# vsUTCS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# vsUTCS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vsUTCS.  If not, see <https://www.gnu.org/licenses/>.


set -e

echo "------------------------------"
echo "--- bootstrap | 2026-07-13 ---"
echo "------------------------------"

platform="$(uname | tr '[:upper:]' '[:lower:]')"

case "$platform" in
    "linux"|"linux-gnu")
        echo "Bootstrapping on Linux..."
        if [ -f ./scripts/bootstrap-on-linux.sh ] && [ -x ./scripts/bootstrap-on-linux.sh ]
        then
            ./scripts/bootstrap-on-linux.sh "$1"
        elif [ -f ./bootstrap-on-linux.sh ] && [ -x ./bootstrap-on-linux.sh ]
        then
            ./bootstrap-on-linux.sh "$1"
        else
            echo "Error locating bootstrap-on-linux.sh"
            exit 3
        fi
        ;;
    "darwin")
        echo "Bootstrapping on macOS X or later..."
        if [ -f ./scripts/bootstrap-on-macOS.sh ] && [ -x ./scripts/bootstrap-on-macOS.sh ]
        then
            ./scripts/bootstrap-on-macOS.sh "$1"
        elif [ -f ./bootstrap-on-macOS.sh ] && [ -x ./bootstrap-on-macOS.sh ]
        then
            ./bootstrap-on-macOS.sh "$1"
        else
            echo "Error locating bootstrap-on-macOS.sh"
            exit 3
        fi
        ;;
    *)
        echo "Sorry, unrecognized or unsupported operating system"
        exit 2
        ;;
esac
